name: Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev
          - test
          - stage
          - prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify your Terraform version

      - name: Terraform Init
        working-directory: ${{ github.workspace }}/${{ matrix.environment }}
        run: terraform init

      - name: Terraform Plan
        id: terraform-plan
        working-directory: ${{ github.workspace }}/${{ matrix.environment }}
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: ${{ github.workspace }}/${{ matrix.environment }}/tfplan


