name: Terraform

on:
  push:
    branches:
      - master
  workflow_dispatch:
  inputs:
    environment:
      description: 'Environment to deploy'
      required: true
      default: 'dev'
      type: choice
      options:
        - dev
        - test
        - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify your Terraform version

      - name: Terraform Init
        working-directory: ${{ github.workspace }}
        run: terraform init
      
      - name: PWD
        run: ${{pwd}}
      - name: Terraform Plan
        id: terraform-plan
        working-directory: ${{ github.workspace }}
        run: terraform plan -var-file="{{ github.event.inputs.environment }}-terraform.tfvars"

     


